puzzle:
	java -jar tsa-cli.jar custom-checker --fift-std ../fiftlib -o output/puzzle.sarif --checker checker.fc -c Tact tact.config.json Puzzle PeekLevel

puzzleFromBoc:
	java -jar tsa-cli.jar custom-checker --fift-std ../fiftlib -o output/puzzle.sarif --checker checker.fc -c Boc output/Puzzle_PeekLevel.code.boc